services:
  database:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: pagamentoApiUser
      POSTGRES_PASSWORD: P4a55w0rd
      POSTGRES_DB: dotlanche-pagamento
    ports:
      - "5432:5432"
    volumes:
      - dotLanchesDb:/var/lib/postgresql/data

  mock:
    hostname: mock-pedido
    image: jkris/mountebank:latest
    volumes:
    - ./mockFiles:/imposters
    ports:
    - 2525:2525
    - 8001:8001
    command: --configfile /imposters/imposters.ejs --allowInjection

  api:
    build: 
      context: .
      dockerfile: ./src/Drivers/Dotlanche.Pagamento.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=dotlanche-pagamento;Username=pagamentoApiUser;Password=P4a55w0rd
      - Integrations__PedidoService__BaseAddress=http://mock-pedido:8001

volumes:
  dotLanchesDb:
    name: "dotLanchesDb"
