services:
  database:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: pagamentoApiUser
      POSTGRES_PASSWORD: P4a55w0rd
      POSTGRES_DB: dotlanche-pagamento
    ports:
      - "5432:5432"
    volumes:
      - dotLanchesDb:/var/lib/postgresql/data

  mock:
    hostname: mock-pedido
    image: jkris/mountebank:latest
    volumes:
    - ./mockFiles:/imposters
    ports:
    - 2525:2525
    - 8001:8001
    command: --configfile /imposters/imposters.ejs --allowInjection

  jaeger:
    hostname: jaeger
    image: jaegertracing/all-in-one
    ports:
    - "16686:16686"
    - "4317:4317"
    - "4318:4318"
    - "14250:14250"
    - "14268:14268"
    - "14269:14269"
    - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411

  api:
    build: 
      context: .
      dockerfile: ./src/Drivers/Dotlanche.Pagamento.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=dotlanche-pagamento;Username=pagamentoApiUser;Password=P4a55w0rd
      - Integrations__PedidoService__BaseAddress=http://mock-pedido:8001
      - OpenTelemetry__ProviderEndpointUrl=http://jaeger:4317/

volumes:
  dotLanchesDb:
    name: "dotLanchesDb"
