services:
  database:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: pagamentoApiUser
      POSTGRES_PASSWORD: P4a55w0rd
      POSTGRES_DB: dotlanche-pagamento
    ports:
      - "5432:5432"
    volumes:
      - dotLanchesDb:/var/lib/postgresql/data

  api:
    build: 
      context: .
      dockerfile: ./src/Drivers/Dotlanche.Pagamento.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=dotlanche-pagamento;Username=pagamentoApiUser;Password=P4a55w0rd

volumes:
  dotLanchesDb:
    name: "dotLanchesDb"
