name: CI
on:
  pull_request:

jobs:
  build_test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - id: build
      name: Build
      run: dotnet build --no-restore

    - id: unit_test
      name: Run Unit Tests
      working-directory: ./test/UnitTests/Dotlanche.Pagamento.UnitTests
      run: dotnet test

    - id: bdd_test
      name: Run BDD Tests
      working-directory: ./test/BDD/Dotlanche.Pagamento.BDDTests
      run: dotnet test
  
  validate-docker:
    name: "Validate Dockerfile"
    needs: build_test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Dockerfile
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./src/Drivers/Dotlanche.Pagamento.WebApi/Dockerfile
        push: false
